id = "ktrz-monokai"
name = "KTRZ Monokai Theme"
version = "0.0.4"
schema_version = 1
authors = ["Minh Pham <pcminh0505@gmail.com>"]
description = "KTRZ Monokai Theme for Zed"
repository = "https://github.com/pcminh0505/ktrz-monokai-zed-theme"